# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=8)),
                ('playlistLength', models.IntegerField(default=5)),
                ('expiration', models.DateField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_dj.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('music_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smart_dj.Music')),
                ('ID', models.TextField()),
            ],
            bases=('smart_dj.music',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('music_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smart_dj.Music')),
            ],
            bases=('smart_dj.music',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('music_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smart_dj.Music')),
                ('ID', models.TextField()),
            ],
            bases=('smart_dj.music',),
        ),
        migrations.AddField(
            model_name='person',
            name='dislikes',
            field=models.ManyToManyField(related_name='person_dislikes', to='smart_dj.Music'),
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(related_name='person_likes', to='smart_dj.Music'),
        ),
    ]
